package com.icyapps.moodtracker.domain.model

enum class AppError {
    MOOD_ALREADY_SUBMITTED,
    INVALID_REQUEST,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    SERVER_ERROR,
    NETWORK_ERROR,
    UNKNOWN_ERROR,
    FAILED_TO_LOAD_MOOD_TYPES,
    FAILED_TO_SUBMIT_MOOD,
    FAILED_TO_LOAD_HISTORY
} 